core/urls.py
from django.contrib import admin
from django.urls import include, path
from sfbot.views import MyPasswordChangeView

handler404 = "sfbot.views.error_404"

handler500 = "sfbot.views.error_500"

handler403 = "sfbot.views.error_404"

handler400 = "sfbot.views.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("sfbot.urls", "sfbot"))),
    path("password/change/", MyPasswordChangeView.as_view(),
         name="account_change_password"),
    path("", include("allauth.urls")),
]

sfbot/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home_view, name="index"),
    path("dashboard", views.dashboard_add_bot_view, name="dashboard"),
    path("<int:pk>", views.SettingsView.as_view(), name="settings"),
    path("<int:pk>", views.UserBotDetails.as_view(), name="bot-detail"),
    path("edit/<int:pk>", views.EditBotDetails.as_view(), name="edit-bot"),
    path("profile", views.profile_view, name="profile"),
    path("complete", views.paymentComplete, name="complete"),
    path("shop", views.shop_view, name="shop"),
    path("plan_modal", views.plan_modal, name="plan_modal"),
    path("currency", views.currency, name="currency"),
    path("plan", views.plan_buy, name="plan"),
    path("faq", views.Faq.as_view(), name="faq"),
    path("regulations", views.Regulations.as_view(), name="regulations"),
    path("privacy-policy", views.PrivacyPolicy.as_view(), name="privacy-policy"),
]

sfbot/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class GeneratePage(models.Model):
    def __str__(self):
        return self


class FaqList(models.Model):
    topic = models.CharField(max_length=70)
    description = models.TextField()

    def __str__(self):
        return self.topic


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey("sfbot.Plan", on_delete=models.CASCADE, null=True)
    wallet = models.IntegerField(null=True, default=0)
    create_account = models.DateTimeField(null=True, blank=True)
    plan_start_date = models.DateTimeField(blank=True, null=True)
    plan_expiration_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Currency(models.Model):
    price = models.IntegerField(null=True)
    value = models.IntegerField(null=True)

    class Meta:
        verbose_name_plural = "Currency"

    def __str__(self):
        return str(self.value)


class Orders(models.Model):
    profile = models.ForeignKey(
        "sfbot.Profile", on_delete=models.CASCADE, null=True)
    order_create = models.DateTimeField(auto_now=True, null=True)
    currency_package = models.ForeignKey(
        "sfbot.Currency", on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Orders"


class Plan(models.Model):
    NAME = (
        ("STARTER", "STARTER"),
        ("STANDARD", "STANDARD"),
        ("PREMIUM", "PREMIUM"),
    )
    name = models.CharField(max_length=21, choices=NAME, default="STARTER")
    price = models.IntegerField()
    permission_list = models.ManyToManyField("sfbot.PermissionList")
    special_style = models.CharField(max_length=15, null=True, blank=True)
    max_time = models.FloatField(null=True)
    max_bots = models.IntegerField(null=True)
    available = models.BooleanField(
        verbose_name="Plan is available", default=True)

    def __str__(self):
        return self.name


class PermissionList(models.Model):
    NAME = (
        ("6h", "6h"),
        ("1bot", "1bot"),
        ("12h no", "12h no"),
        ("3bots no", "3bots no"),
        ("12h yes", "12h yes"),
        ("3bots yes", "3bots yes"),
        ("24h no", "24h no"),
        ("5bots no", "5bots no"),
        ("24h yes", "24h yes"),
        ("5bots yes", "5bots yes"),
    )
    ICON = (
        ("check icon", "check icon"),
        ("times icon", "times icon"),
    )
    DESCRIPTION = (
        ("Bot works 6h per day", "Bot works 6h per day"),
        ("Max 1 bot", "Max 1 bot"),
        ("Bot works 12h per day", "Bot works 12h per day"),
        ("Max 3 bots", "Max 3 bots"),
        ("Bot works all the time", "Bot works all the time"),
        ("Max 5 bot", "Max 5 bot"),
    )
    name = models.CharField(max_length=40, choices=NAME)
    icon = models.CharField(max_length=40, choices=ICON)
    description = models.CharField(max_length=40, choices=DESCRIPTION)

    def __str__(self):
        return self.name


class Bots(AbstractBaseUser):
    TAVERN = (
        ("Gold", "Gold"),
        ("Exp", "Exp"),
        ("Time", "Time"),
    )
    ARENA = (
        ("Stop fight after 10 wins", "Stop fight after 10 wins"),
        (
            "Attack opponents who have items for your cluster",
            "Attack opponents who have items for your cluster",
        ),
    )
    COUNTRY = (("Intercontinental", "Intercontinental"),)
    SERVER = (
        ("s1", "s1"),
        ("s2", "s2"),
        ("s3", "s3"),
        ("s4", "s4"),
        ("s5", "s5"),
    )
    profile = models.ForeignKey(
        "sfbot.Profile", on_delete=models.CASCADE, null=True)
    status = models.BooleanField(verbose_name="Bot status", default=False)
    time_left = models.TimeField(null=True)
    converted_time = models.FloatField(null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    stop = models.DateTimeField(null=True, blank=True)

    username = models.CharField(
        verbose_name="SF Username", max_length=40, null=True)
    password = models.CharField(
        verbose_name="SF Password", max_length=30, null=True)
    country = models.CharField(
        max_length=20, choices=COUNTRY, default="Intercontinental", null=True
    )
    server = models.CharField(max_length=4, choices=SERVER, null=True)

    tavern_status = models.BooleanField(
        verbose_name="Tavern status", default=False)
    tavern_settings = models.CharField(
        max_length=4, choices=TAVERN, default="Exp")
    arena_status = models.BooleanField(
        verbose_name="Arena status", default=False)
    arena_settings = models.CharField(
        max_length=50, choices=ARENA, default="Stop fight after 10 wins"
    )

    USERNAME_FIELD = "username"

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _("bots")
        verbose_name_plural = _("Bots")

    def get_absolute_url(self):
        return reverse("sfbot:settings", kwargs={"pk": self.pk})

sfbot/views.py
from allauth.account.views import PasswordChangeView
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from .forms import AddBotForm, SettingsForm, EditBotForm, UserSettingsForm
from .models import Bots, FaqList, GeneratePage, Plan, Profile, User, PermissionList, Currency, Orders
from django.contrib import messages
import json
from django.utils import timezone
from datetime import timedelta


def error_404(request, exception):
    return render(request, "404.html")


def error_500(request):
    return render(request, "404.html")


def home_view(request):
    plans = Plan.objects.all()
    users = User.objects.all().count()
    bots = Bots.objects.all().count()
    working_bots = Bots.objects.filter(status=True).count()
    plan_list = Plan.objects.all()
    permission_list = PermissionList.objects.all()

    if not permission_list:
        w_6 = PermissionList(name="6h", icon="check icon",
                             description="Bot works 6h per day")
        w_6.save()
        m_1 = PermissionList(name="1bot", icon="check icon",
                             description="Max 1 bot")
        m_1.save()
        w_12_n = PermissionList(
            name="12h no", icon="times icon", description="Bot works 12h per day")
        w_12_n.save()
        m_3_n = PermissionList(
            name="3bots no", icon="times icon", description="Max 3 bots")
        m_3_n.save()
        w_12_y = PermissionList(
            name="12h yes", icon="check icon", description="Bot works 12h per day")
        w_12_y.save()
        m_3_y = PermissionList(
            name="3bots yes", icon="check icon", description="Max 3 bots")
        m_3_y.save()
        w_24_n = PermissionList(
            name="24h no", icon="times icon", description="Bot works all the time")
        w_24_n.save()
        m_5_n = PermissionList(
            name="5bots no", icon="times icon", description="Max 5 bot")
        m_5_n.save()
        w_24_y = PermissionList(
            name="24h yes", icon="check icon", description="Bot works all the time")
        w_24_y.save()
        m_5_y = PermissionList(
            name="5bots yes", icon="check icon", description="Max 5 bot")
        m_5_y.save()
    if not plan_list:
        starter = Plan(name="STARTER", price="0", max_time="6", max_bots="1")
        starter.save()
        starter.permission_list.add(w_6, m_1, w_12_n, m_3_n, w_24_n, m_5_n)

        standard = Plan(name="STANDARD", price="4",
                        special_style="best", max_time="12", max_bots="3")
        standard.save()
        standard.permission_list.add(w_6, m_1, w_12_y, m_3_y, w_24_n, m_5_n)

        premium = Plan(name="PREMIUM", price="8", max_time="24", max_bots="5")
        premium.save()
        premium.permission_list.add(w_6, m_1, w_12_y, m_3_y, w_24_y, m_5_y)

    context = {
        "plans": plans,
        "users": users,
        "bots": bots,
        "working_bots": working_bots,
    }
    return render(request, "home.html", context)


def dashboard_add_bot_view(request):
    # Dashboard
    bots_q = Bots.objects.all()
    user_bots = bots_q.filter(profile__user=request.user)
    current_user = Profile.objects.filter(user=request.user)

    if not current_user:
        starter_plan = Plan.objects.get(name="STARTER")
        user_profile = Profile(
            user=request.user, plan=starter_plan, create_account=timezone.now(), plan_start_date=timezone.now())
        user_profile.save()

    amount_user_bots = user_bots.count()
    current_plan_q = Plan.objects.get(
        profile=(Profile.objects.get(user=request.user)))
    if amount_user_bots >= current_plan_q.max_bots:
        lock_add = True
    else:
        lock_add = False

    # Add Bot
    form = AddBotForm()
    if request.method == "POST":
        form = AddBotForm(request.POST)
        if form.is_valid():
            # check if user profile is created
            current_user = Profile.objects.filter(user=request.user)
            if current_user:
                # amount of all bots for current user
                max_user_bots = Bots.objects.filter(
                    profile__user=request.user).count()
                # acces to user current plan query
                current_plan_q = Plan.objects.get(
                    profile=(Profile.objects.get(user=request.user))
                )
                if max_user_bots < current_plan_q.max_bots:
                    obj = form.save(commit=False)
                    # Set current user profile
                    obj.profile = Profile.objects.get(user=request.user)
                    # Convert float form plan to time in bot
                    if current_plan_q.max_time == 24.0:
                        obj.time_left = "{0:02.0f}:{1:02.0f}".format(
                            *divmod(float("23.99") * 60, 60)
                        )
                    else:
                        obj.time_left = "{0:02.0f}:{1:02.0f}".format(
                            *divmod(float(current_plan_q.max_time) * 60, 60)
                        )
                        obj.converted_time = current_plan_q.max_time
                    obj.save()
                    messages.add_message(
                        request, messages.SUCCESS, 'A new bot has been added.')
                    return HttpResponseRedirect(obj.get_absolute_url())

    context = {
        "user_bots": user_bots,
        "lock_add": lock_add,
        "form": form,
    }

    return render(request, "user/dashboard.html", context)


def profile_view(request):
    current_user = Profile.objects.filter(user=request.user)

    if current_user:
        max_user_bots = Bots.objects.filter(profile__user=request.user).count()
        user_profile = Profile.objects.get(user=request.user)
        if max_user_bots != 0:
            current_user_qs = Bots.objects.filter(profile__user=request.user)
        else:
            current_user_qs = User.objects.filter(username=request.user)
    else:
        current_user_qs = User.objects.filter(username=request.user)

    user_data = User.objects.get(username=request.user)
    form = UserSettingsForm()
    if request.method == "POST":
        form = UserSettingsForm(request.POST, instance=request.user)
        if form.is_valid():
            username = form.cleaned_data["username"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]

            obj = form.save(commit=False)

            if not username:
                obj.username = user_data.username
            if not first_name:
                obj.first_name = user_data.first_name
            if not last_name:
                obj.last_name = user_data.last_name
            if not email:
                obj.email = user_data.email
            messages.add_message(request, messages.SUCCESS,
                                 'Profile details updated.')
            obj.save()
            form = UserSettingsForm()
        else:
            messages.add_message(request, messages.ERROR,
                                 'Wrong data provided')

    context = {
        "current_user_qs": current_user_qs,
        "form": form,
        "user_profile": user_profile
    }

    return render(request, "user/profile.html", context)


def paymentComplete(request):
    body_data = json.loads(request.body)
    currency_id = body_data['productId']
    profile_id = body_data['userProfile']
    currency_object = Currency.objects.get(id=currency_id)
    profile_object = Profile.objects.get(id=profile_id)
    Orders.objects.create(profile=profile_object,
                          currency_package=currency_object)

    if currency_id and profile_id:
        profile_object.wallet += currency_object.value
        profile_object.save()
        messages.add_message(request, messages.SUCCESS,
                             "Successfully purchased: " + str(currency_object))

    return JsonResponse('Payment completed!', safe=False)


def shop_view(request):
    plans = Plan.objects.all()
    user_profile = Profile.objects.get(user=request.user)
    starter_plan = Plan.objects.get(name="STARTER")
    user_plan = user_profile.plan.name
    currency = Currency.objects.all()
    lock = False
    if user_profile.plan_expiration_date:
        time_to_end = str(user_profile.plan_expiration_date -
                          user_profile.plan_start_date)
        if time_to_end != "0:00:00":
            lock = True
        else:
            if user_profile.plan != starter_plan:
                user_profile.plan = starter_plan
                user_profile.save()

    context = {
        "plans": plans,
        "user_plan": user_plan,
        "currency": currency,
        "user_profile": user_profile,
        "lock": lock,
    }
    return render(request, "user/shop.html", context)


def currency(request):
    body_data = json.loads(request.body)
    currency_id = body_data['productId']
    product = Currency.objects.get(id=currency_id)
    price = str(product.price)
    value = str(product.value)
    data = {
        'price': price,
        'value': value,
    }
    return JsonResponse(data)


def plan_modal(request):
    body_data = json.loads(request.body)
    modal_id = body_data['modalId']
    modal_object = Plan.objects.get(id=modal_id)
    name = str(modal_object.name)
    price = str(modal_object.price)

    modal_data = {
        'name': name,
        'price': price,
        'id': modal_id,
    }

    return JsonResponse(modal_data)


def plan_buy(request):
    body_data = json.loads(request.body)
    plan_id = body_data['planId']
    plan_product = Plan.objects.get(id=plan_id)

sfbot/templates/user/dashboard.html
{% extends "layouts/default.html" %}

{% load static %}

{% block title %}SFBot - Dashboard{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="wrapper">
    {% include "layouts/sidebar.html" %}
    {% include "layouts/mobile-sidebar.html" %}
    {% include "modal/quit.html" %}
    {% include "modal/add-bot.html" %}
    <div class="user-content">
      <div class="nav-col">
        <nav class="nav-right">
          <div class="container-fluid">
            {% if lock_add == False %}
              <div class="item nav-links add">
                <i class="plus icon"></i>
                Add Bot
              </div>
            {% else %}
              <div class="item nav-links max">
                <i class="times icon"></i>
                Max Bots
              </div>
            {% endif %}
            <div class="ui dropdown">
              <div class="account">{{ user }}</div>
              <i class="dropdown icon"></i>
              <div class="menu">
                <div class="item nav-links quit">
                  <i class="sign out alternate icon"></i>
                  Logout
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <script src="{% static 'js/navbar.js' %}"></script>
      <script src="{% static 'js/modal.js' %}"></script>


      <h1 class="text-center">Dashboard</h1>
      <div class="bots">
        {% if user_bots  %}
          {% for bot in user_bots  %}
            <div class="bot">
              <div class="header-name text-center">
                {{ bot.username }}
              </div>
              {% if bot.status == True %}
                <div class="status">
                  <b> Status:</b> <br> Bot is in a fight <img src="{% static 'img/status/work.png' %}">
                </div>
              {% else %}
                <div class="status">
                  <b> Status:</b> <br> Bot waiting for a combat task <img src="{% static 'img/status/wait.png' %}">
                </div>
              {% endif %}
              <div class="settings">
                <a href="{{ bot.get_absolute_url }}">Settings</a>
              </div>
              {% if bot.status == True %}
                <div class="status-color-on"></div>
              {% else %}
                <div class="status-color-off"></div>
              {% endif %}
            </div>
          {% endfor %}
        {% else %}
          <div class="text-center no-bots">
            You don't have any bots, click on "Add Bot", at the top of the page. <br><br>
            If you are using the mobile version, go to the menu and click "Add Bot".
          </div>
        {% endif %}
      </div>
      {% include "layouts/footer-user.html" %}
    </div>
  {% else %}
  <div class="background">
    <div class="custom-form space">
      <ul class="tab-group">
        <li class="tab"><a href="signup">Sign Up</a></li>
        <li class="tab active"><a href="login">Log In</a></li>
      </ul>
      <div id="login">
        <h1 class="white">You aren't logged in</h1>
        <p class="white bigger-p text-center space-p"> Go to "Log In" or if you don't have account, <br> go to "Sign Up"</p>
      </div>
    </div>
  </div>
  {% endif %}
  </div>
  {% include "modal/toasts.html" %}
{% endblock %}

sfbot/templates/user/edit-bot.html
{% extends "layouts/default.html" %}

{% load static %}

{% block title %}SFBot - Edit Bot Settings{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="wrapper">
      {% include "layouts/sidebar.html" %}
      {% include "layouts/mobile-sidebar.html" %}
      <div class="user-content">
        {% include "layouts/navbar.html" %}
        <h1 class="text-center">Edit Bot Information</h1>
        <form action="" method="post" class="bot-settings">
        {% csrf_token %}
        <div class="edit-information">
          <div class="left">
            <div class="item">
              <div class="object">SF username:</div>
              <div class="object">{{ form.username }}</div>
            </div>
            <div class="item">
              <div class="object">Account country:</div>
              <div class="object">{{ form.country }}</div>
            </div>
          </div>
          <div class="right">
            <div class="item"> 
              <div class="object">SF Password:</div>
              <div class="object">{{ form.password }}</div>
            </div>
            <div class="item">
              <div class="object">Account server:</div>
              <div class="object">{{ form.server }}</div>
            </div>
          </div>
        </div>
        {{ form.non_field_errors }}
        <button class="button button-block" type="submit">Save Settings</button>
        </form>
  {% else %}
    <div class="background">
      <div class="custom-form space">
        <ul class="tab-group">
          <li class="tab"><a href="signup">Sign Up</a></li>
          <li class="tab active"><a href="login">Log In</a></li>
        </ul>
        <div id="login">
          <h1 class="white">You aren't logged in</h1>
          <p class="white bigger-p text-center space-p"> Go to "Log In" or if you don't have account, <br> go to "Sign Up"</p>
        </div>
      </div>
    </div>
  {% endif %}
    </div>
{% endblock %}

sfbot/templates/user/faq.html
{% extends "layouts/default.html" %}

{% load static %}

{% block title %}SFBot - FAQ{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="wrapper">
    {% include "layouts/sidebar.html" %}
    {% include "layouts/mobile-sidebar.html" %}
    <div class="user-content">
      {% include "layouts/navbar.html" %}
      <h1 class="text-center">FAQ</h1>
      {% if not faqs %}
        <h1 class="text-center">At the moment faqs are empty.</h1>
      {% else %}
      <div class="ui styled accordion">
        {% for faq in faqs %}
          <div class="title">
            <i class="dropdown icon"></i>
            {{ faq.topic }}
          </div>
          <div class="content">
            <p>{{ faq.description }}</p>
          </div>
        {% endfor %}
      </div>
      {% endif %}
    {% include "layouts/footer-user.html" %}
    </div>


  <script src="{% static 'js/faq.js' %}"></script>
  {% else %}
  <div class="background">
    <div class="form-reg-log">
      <h1 class="white">You aren't logged in. Go to: <br><a href="login">Login section</a></h1>
    </div>
  </div>
  {% endif %}
  </div>
{% endblock %}

sfbot/templates/user/settings.html
{% extends "layouts/default.html" %}

{% load static %}

{% block title %}SFBot - Bot Settings{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="wrapper">
    {% include "layouts/sidebar.html" %}
    {% include "layouts/mobile-sidebar.html" %}
    <div class="user-content">
      {% include "layouts/navbar.html" %}
      <form action="" method="post" class="bot-settings">
        {% csrf_token %}
        <h1 class="text-center">Bot Status</h1>
        <div class="status">
          <div class="onoffswitch">
            {% if object.time_left|time:"H:i" != '00:00' %}
              {{ form.status }}
              <label class="onoffswitch-label" for="id_status">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            {% else %}
              {% if object.status == True %}
                {{ form.status }}
                <label class="onoffswitch-label" for="id_status">
                  <span class="onoffswitch-inner"></span>
                  <span class="onoffswitch-switch"></span>
                </label>
              {% else %}
                <label class="onoffswitch-label max" for="id_status">
                  <span class="onoffswitch-inner"></span>
                  <span class="onoffswitch-switch"></span>
                </label>
              {% endif %}
            {% endif %}
          </div>
          {% if object.time_left|time:"H:i" == '00:00' %}
            <p class="time-error text-center">
              You have used up the package, wait until the next day for its renewal!
            </p>
          {% endif %}
        </div>


        <h1 class="text-center">Information (<a href="/edit{{ object.get_absolute_url }}">Edit</a>) </h1>
        <div class="information-account">
          <div class="left">
            <div class="item">
              <div class="desc">SF username:</div>
              <div class="object">{{ object.username }}</div>
            </div>
            <div class="item">
              <div class="desc">Bot will stop at:</div>
              <div class="object">
                {% if object.stop %}
                  {{ object.stop|date:"d.m g:i A" }}
                {% else %}
                  {% if object.profile.plan.name == "PREMIUM" %}
                    Time Unlimited
                  {% else %}
                    {% if object.status %}
                      Calculating...
                    {% else %}
                      ????
                    {% endif %}
                  {% endif %}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="right">
            <div class="item"> 
              <div class="desc">Account country:</div> 
              <div class="object">{{ object.country }}</div>
            </div>
            <div class="item"> 
              <div class="desc">Account server:</div>
              <div class="object">{{ object.server }}</div>
            </div>
          </div>
        </div>


        <h1 class="text-center"> Settings </h1>
        <div class="section">
          <div class="work">
            <div class="onoffswitch">
              {{ form.tavern_status }}
              <label class="onoffswitch-label" for="id_tavern_status">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
          <div class="task text-center">
            <h1>Tavern</h1>
            <div class="choose">
              Prefer: {{ form.tavern_settings }}
            </div>
          </div>
        </div>


        <div class="section">
          <div class="work">
            <div class="onoffswitch">
              {{ form.arena_status }}
              <label class="onoffswitch-label" for="id_arena_status">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
          <div class="task text-center">
            <h1>Arena</h1>
            <div class="choose">
              Choose opponents: {{ form.arena_settings }}
            </div>
          </div>
        </div>

        {{ form.non_field_errors }}
        <button class="button button-block" type="submit">Save Settings</button>
      </form>
    {% include "layouts/footer.html" %}
    </div>
  {% else %}
  <div class="background">
    <div class="custom-form space">
      <ul class="tab-group">
        <li class="tab"><a href="signup">Sign Up</a></li>
        <li class="tab active"><a href="login">Log In</a></li>
      </ul>
      <div id="login">
        <h1 class="white">You aren't logged in</h1>
        <p class="white bigger-p text-center space-p"> Go to "Log In" or if you don't have account, <br> go to "Sign Up"</p>
      </div>
    </div>
  </div>
  {% endif %}
  </div>
  {% include "modal/toasts.html" %}
{% endblock %}